"""delivery_attempts and outbox index

Revision ID: 75ef2b34c3fb
Revises: 1f72cef1e05f
"""
from alembic import op
import sqlalchemy as sa


revision = '75ef2b34c3fb'
down_revision = '1f72cef1e05f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outbox_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chatwoot_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outbox_id'], ['outbox_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_conversation_status', 'outbox_messages', ['conversation_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_conversation_status', table_name='outbox_messages')
    op.drop_table('delivery_attempts')
    # ### end Alembic commands ###
