"""core tables

Revision ID: c832da65db01
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c832da65db01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('brand_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('chatwoot_inbox_id', sa.Integer(), nullable=True),
    sa.Column('automation_default', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatwoot_inbox_id')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('platform_account_id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_account_id', 'external_user_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('brand_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('platform_account_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('conversation_key', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'conversation_key')
    )
    op.create_table('automation_states',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('human_agent_id', sa.Text(), nullable=True),
    sa.Column('last_human_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bot_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_policy', sa.Text(), nullable=False),
    sa.Column('state_changed_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('conversation_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatwoot_account_id', sa.Integer(), nullable=False),
    sa.Column('chatwoot_conversation_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatwoot_account_id', 'chatwoot_conversation_id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('sender_type', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('chatwoot_message_id', sa.BigInteger(), nullable=True),
    sa.Column('platform_message_id', sa.Text(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chatwoot_message_id'), 'messages', ['chatwoot_message_id'], unique=False)
    op.create_index(op.f('ix_messages_platform_message_id'), 'messages', ['platform_message_id'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('platform_account_id', sa.UUID(), nullable=False),
    sa.Column('destination_type', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_message_id', sa.Text(), nullable=True),
    sa.Column('chatwoot_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_messages_chatwoot_message_id'), 'outbox_messages', ['chatwoot_message_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_platform_message_id'), 'outbox_messages', ['platform_message_id'], unique=False)
    op.create_table('normalized_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('platform_account_id', sa.UUID(), nullable=False),
    sa.Column('external_event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('raw_event_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', 'platform_account_id', 'external_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normalized_events')
    op.drop_index(op.f('ix_outbox_messages_platform_message_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_chatwoot_message_id'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_messages_platform_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chatwoot_message_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversation_mappings')
    op.drop_table('automation_states')
    op.drop_table('conversations')
    op.drop_table('contacts')
    op.drop_table('raw_events')
    op.drop_table('platform_accounts')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
